### ISSUE TITLE
About the error reported after the pre-trained model is loaded

### ISSUE THREAD

**Issue by irinaxu** [sp-uhh/storm#4]
Thank you very much for sharing!!  I used the ckpt shared by the project to try and test, but an error occurred. 
**parameter settings**
for parser_ in (base_parser, parser):
	parser_.add_argument("--test_dir", type=str, default = '/reverb/', help="Directory containing your corrupted files to enhance.")
	parser_.add_argument("--enhanced_dir", type=str, default = '/reverb_out/', help="Where to write your cleaned files.")
	parser_.add_argument("--ckpt", type=str,default = 'logs/epoch=237-pesq=0.00.ckpt')
	parser_.add_argument("--mode",default="regen", choices=["score-only", "denoiser-only", "regen-freeze-denoiser", "regen-joint-training"])

	parser_.add_argument("--corrector", type=str, choices=("ald", "langevin", "none"), default="ald", help="Corrector class for the PC sampler.")
	parser_.add_argument("--corrector-steps", type=int, default=1, help="Number of corrector steps")
	parser_.add_argument("--snr", type=float, default=0.5, help="SNR value for (annealed) Langevin dynamics.")
	parser_.add_argument("--N", type=int, default=50, help="Number of reverse steps")
**error：**

![image](https://user-images.githubusercontent.com/42988609/221841212-b91d545d-8569-423b-83d4-1532b8f6b3f5.png)

**Comment by jmlemercier** [comment]
Dear Irina, thanks for reporting: I had indeed changed one line in ncsnpp.py to remove some modules which are useless when using the NCSN++ backbone in discriminative mode, but that messed up the checkpoint compatibility (I just reverted, because I could not fix it easily as the ncsnpp class is taken from Song's code and is very messy, will consider rewriting it in the future)

Best,
Jm
