### ISSUE TITLE
Value of command line param mode for dereverberation

### ISSUE THREAD

**Issue by adeelabbas** [sp-uhh/storm#7]
Hi,
Can you share what value of mode command line flag should be set for dereverberation and enhancement use cases?

Thanks,
Adeel

**Comment by jmlemercier** [comment]
Dear Adeel,
The `mode` flag is used to call a specific Model class in `model.py` .
I changed it with the last commit so that it is even more explicit now, the right use for it therefore: 
`--mode score-only` if you are using a SGMSE+ checkpoint
`--mode denoiser-only` if you are using a NCSN++M checkpoint
`--mode storm` if you are using a StoRM checkpoint

Best,
Jim
